// Code generated by protoc-gen-go.
// source: data/data.proto
// DO NOT EDIT!

/*
Package octo is a generated protocol buffer package.

It is generated from these files:
	data/data.proto

It has these top-level messages:
	Data
	Database
*/
package octo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Data_State int32

const (
	Data_NONE   Data_State = 0
	Data_ADD    Data_State = 1
	Data_UPDATE Data_State = 2
	Data_LATEST Data_State = 3
	Data_DELETE Data_State = 4
)

var Data_State_name = map[int32]string{
	0: "NONE",
	1: "ADD",
	2: "UPDATE",
	3: "LATEST",
	4: "DELETE",
}
var Data_State_value = map[string]int32{
	"NONE":   0,
	"ADD":    1,
	"UPDATE": 2,
	"LATEST": 3,
	"DELETE": 4,
}

func (x Data_State) Enum() *Data_State {
	p := new(Data_State)
	*p = x
	return p
}
func (x Data_State) String() string {
	return proto.EnumName(Data_State_name, int32(x))
}
func (x *Data_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Data_State_value, data, "Data_State")
	if err != nil {
		return err
	}
	*x = Data_State(value)
	return nil
}

// 単体のAssetBundle情報
type Data struct {
	Id               *int32      `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Filepath         *string     `protobuf:"bytes,2,opt,name=filepath" json:"filepath,omitempty"`
	Name             *string     `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Size             *int32      `protobuf:"varint,4,req,name=size" json:"size,omitempty"`
	Crc              *uint32     `protobuf:"varint,5,opt,name=crc" json:"crc,omitempty"`
	Md5              *string     `protobuf:"bytes,10,req,name=md5" json:"md5,omitempty"`
	Priority         *int32      `protobuf:"varint,6,opt,name=priority" json:"priority,omitempty"`
	Tagid            []int32     `protobuf:"varint,7,rep,name=tagid" json:"tagid,omitempty"`
	Dependencie      []int32     `protobuf:"varint,8,rep,name=dependencie" json:"dependencie,omitempty"`
	ObjectName       *string     `protobuf:"bytes,11,req,name=objectName" json:"objectName,omitempty"`
	Generation       *uint64     `protobuf:"varint,12,opt,name=generation" json:"generation,omitempty"`
	UploadVersionId  *int32      `protobuf:"varint,13,opt,name=uploadVersionId" json:"uploadVersionId,omitempty"`
	State            *Data_State `protobuf:"varint,9,opt,name=state,enum=octo.Data_State,def=0" json:"state,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}

const Default_Data_State Data_State = Data_NONE

func (m *Data) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Data) GetFilepath() string {
	if m != nil && m.Filepath != nil {
		return *m.Filepath
	}
	return ""
}

func (m *Data) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Data) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *Data) GetCrc() uint32 {
	if m != nil && m.Crc != nil {
		return *m.Crc
	}
	return 0
}

func (m *Data) GetMd5() string {
	if m != nil && m.Md5 != nil {
		return *m.Md5
	}
	return ""
}

func (m *Data) GetPriority() int32 {
	if m != nil && m.Priority != nil {
		return *m.Priority
	}
	return 0
}

func (m *Data) GetTagid() []int32 {
	if m != nil {
		return m.Tagid
	}
	return nil
}

func (m *Data) GetDependencie() []int32 {
	if m != nil {
		return m.Dependencie
	}
	return nil
}

func (m *Data) GetObjectName() string {
	if m != nil && m.ObjectName != nil {
		return *m.ObjectName
	}
	return ""
}

func (m *Data) GetGeneration() uint64 {
	if m != nil && m.Generation != nil {
		return *m.Generation
	}
	return 0
}

func (m *Data) GetState() Data_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return Default_Data_State
}

func (m *Data) GetUploadVersionId() int32 {
	if m != nil && m.UploadVersionId != nil {
		return *m.UploadVersionId
	}
	return 0
}

// AssetBundle情報一覧
type Database struct {
	Revision         *int32   `protobuf:"varint,1,req,name=revision" json:"revision,omitempty"`
	AssetBundleList  []*Data  `protobuf:"bytes,2,rep,name=assetBundleList" json:"assetBundleList,omitempty"`
	Tagname          []string `protobuf:"bytes,3,rep,name=tagname" json:"tagname,omitempty"`
	ResourceList     []*Data  `protobuf:"bytes,4,rep,name=resourceList" json:"resourceList,omitempty"`
	UrlFormat        *string  `protobuf:"bytes,5,opt,name=urlFormat" json:"urlFormat,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Database) Reset()         { *m = Database{} }
func (m *Database) String() string { return proto.CompactTextString(m) }
func (*Database) ProtoMessage()    {}

func (m *Database) GetRevision() int32 {
	if m != nil && m.Revision != nil {
		return *m.Revision
	}
	return 0
}

func (m *Database) GetAssetBundleList() []*Data {
	if m != nil {
		return m.AssetBundleList
	}
	return nil
}

func (m *Database) GetTagname() []string {
	if m != nil {
		return m.Tagname
	}
	return nil
}

func (m *Database) GetResourceList() []*Data {
	if m != nil {
		return m.ResourceList
	}
	return nil
}

func (m *Database) GetUrlFormat() string {
	if m != nil && m.UrlFormat != nil {
		return *m.UrlFormat
	}
	return ""
}

func init() {
	proto.RegisterEnum("octo.Data_State", Data_State_name, Data_State_value)
}
