// Code generated by protoc-gen-go.
// source: data/url.proto
// DO NOT EDIT!

/*
Package octo is a generated protocol buffer package.

It is generated from these files:
	data/url.proto

It has these top-level messages:
	Url
	UrlList
*/
package octo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Url_State int32

const (
	Url_LATEST Url_State = 1
	Url_OLD    Url_State = 2
)

var Url_State_name = map[int32]string{
	1: "LATEST",
	2: "OLD",
}
var Url_State_value = map[string]int32{
	"LATEST": 1,
	"OLD":    2,
}

func (x Url_State) Enum() *Url_State {
	p := new(Url_State)
	*p = x
	return p
}
func (x Url_State) String() string {
	return proto.EnumName(Url_State_name, int32(x))
}
func (x *Url_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Url_State_value, data, "Url_State")
	if err != nil {
		return err
	}
	*x = Url_State(value)
	return nil
}

type Url struct {
	Revision         *int32     `protobuf:"varint,1,req,name=revision" json:"revision,omitempty"`
	Url              *string    `protobuf:"bytes,2,req,name=url" json:"url,omitempty"`
	State            *Url_State `protobuf:"varint,3,opt,name=state,enum=octo.Url_State,def=1" json:"state,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Url) Reset()         { *m = Url{} }
func (m *Url) String() string { return proto.CompactTextString(m) }
func (*Url) ProtoMessage()    {}

const Default_Url_State Url_State = Url_LATEST

func (m *Url) GetRevision() int32 {
	if m != nil && m.Revision != nil {
		return *m.Revision
	}
	return 0
}

func (m *Url) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *Url) GetState() Url_State {
	if m != nil && m.State != nil {
		return *m.State
	}
	return Default_Url_State
}

type UrlList struct {
	Url              []*Url `protobuf:"bytes,1,rep,name=url" json:"url,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UrlList) Reset()         { *m = UrlList{} }
func (m *UrlList) String() string { return proto.CompactTextString(m) }
func (*UrlList) ProtoMessage()    {}

func (m *UrlList) GetUrl() []*Url {
	if m != nil {
		return m.Url
	}
	return nil
}

func init() {
	proto.RegisterEnum("octo.Url_State", Url_State_name, Url_State_value)
}
